app/touchcenter/views.py
from flask import Blueprint, Response, flash, session, request, g, render_template, redirect, url_for, jsonify, make_response
from .forms import *
from .models import *
from flask_jwt_extended import create_access_token, verify_jwt_in_request
from ..config import Config as conf







from functools import wraps
import jwt
from flask_jwt_extended import jwt_required
from flask_jwt_extended import jwt_required, get_jwt_identity



home = Blueprint('home', __name__)
articulo = Blueprint('articulo', __name__ , url_prefix = '/articulo')
venta = Blueprint('venta',       __name__ , url_prefix = '/venta')
admin = Blueprint('admin',       __name__ , url_prefix = '/admin')
proveedor = Blueprint('proveedor', __name__ , url_prefix = '/proveedor')
cliente = Blueprint('cliente', __name__ , url_prefix = '/cliente')
servicio = Blueprint('servicio', __name__ , url_prefix = '/servicio')
dash_route = Blueprint('dash_route', __name__ , url_prefix = '/dash')

def token_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        try:
            token = session.get("user")["access_token"]
            if not token:
                flash("error", "Error de sesión! "+str(e))

                return redirect(url_for('home.logout'))
            data = jwt.decode(token, "holaMundo", algorithms=["HS256"])
            # Realiza cualquier otra validación que necesites aquí
        except jwt.ExpiredSignatureError as e:
            print("ERROR GENERANDO EL TOKEN ! "+ str(e))
            flash("error", "Su sesión expiró!")
            session.pop("user", None)  # Elimina la sesión del usuario
            return redirect(url_for('home.logout'))
        except Exception as e:
            print("ERROR DE SESION! "+ str(e))
            #flash("error", ("Su sesión expiró " ))
            return redirect(url_for('home.logout'))

        return f(*args, **kwargs)

    return decorated




@venta.before_request
@admin.before_request
@articulo.before_request
@token_required
def validate_before_request():
    pass

@home.route("/")
@token_required
def index():
    return redirect(url_for('venta.ventas'))


@home.route("/login", methods=["GET", 'POST'])
def login():
    form_login = LoginUsuarioForm()

    if request.method == 'GET':
        resp = make_response(render_template('login.html', form=form_login))
        resp.set_cookie('same-site-cookie', 'foo', samesite='Lax')
        resp.set_cookie('cross-site-cookie', 'bar', samesite='Lax', secure=True)
        return resp

    if request.method == 'POST':
        usuario = form_login.usuario.data
        pwd = form_login.pwd_usuario.data

        user = get_user_by_usuario(usuario)

        if not user:
            print("no existe el usuario")
            flash( 'info',"No existe el usuario")
            return redirect(url_for('home.login'))
        elif user['pwd_usuario'] == pwd:
            #flash('info', "Bienvenido")
            access_token = create_access_token(identity=user["n_usuario"], expires_delta= conf.TOKEN_EXPIRES)
            session["user"] = {"n_usuario":user["n_usuario"],  "access_token":access_token} 
            session["servicios"] = []
            session["items"] = []
            session["cliente"] = []
            print(session["user"])
            return redirect(url_for('home.index'))
        else:
            flash('warning', "Contraseña incorrecta")
            return redirect(url_for('home.login'))

@home.route("/logout",  methods=["GET", 'POST'])
def logout():
    g.user=None
    session.pop("user", None)
    return redirect(url_for('home.login',user=g.user))
        

@home.route("/register", methods=["GET", 'POST'])
def register():
    form_register = RegistroUsuarioForm()

    if request.method == 'GET':
        #resp = make_response()
        #resp.set_cookie('same-site-cookie', 'foo', samesite='Lax')
        #resp.set_cookie('cross-site-cookie', 'bar', samesite='Lax', secure=True)
        return render_template('register.html', form=form_register)

    if request.method == 'POST':
        usuario = form_register.usuario.data
        pwd = form_register.pwd_usuario.data

        user = get_user_by_usuario(usuario)
        if user:
            flash('info', "El usuario ya existe")
            return redirect(url_for('home.register'))
        else:
            user = register_user(usuario,pwd, "admin" )
            if user:
                flash( 'success', "Se registro el usuario "+ user)
                return redirect(url_for('home.login'))
            else:
                flash( 'error', "No se registró el usuario ")
                return redirect(url_for('home.register'))
   

@articulo.route("/", methods=["GET", "POST"])
def articulos():
    return "articulos"

@venta.route("/", methods=["GET", "POST"])
def ventas():
    if request.method == "GET":
        return render_template('ventas.html')

@venta.route("/nuevo", methods=["GET", "POST"])
def nuevaventa():

    form_new_cliente = newClienteForm()
    form_new_articulo = newArticuloForm()
    form_new_proveedor = newProveedorForm()
    form_consultar_cliente = newClienteForm()
    form_new_venta  =newVentaForm()
    proveedores = get_proveedores()
    proveedores_json = [{"label": str(proveedor.id) +" - "+ proveedor.n_proveedor, "value": str(proveedor.id) +" - "+ proveedor.n_proveedor} for proveedor in proveedores]
    if request.method == "GET":
        
        print("LA SESION ESSS ", session)
        return render_template('nuevaVenta2.html', form_new_cliente = form_new_cliente, form_new_articulo = form_new_articulo, form_new_proveedor = form_new_proveedor, form_new_venta = form_new_venta, form_consultar_cliente=form_consultar_cliente, servicios = session["servicios"], proveedores = proveedores, get_articulo_by_id = get_articulo_by_id, subtotal = 0)


@venta.route("/registroventa/<k_cliente>/<k_usuario>", methods=["GET", "POST"])
def registroventa(k_cliente, k_usuario):
        k_cliente = k_cliente
        k_cliente = 1
        k_usuario = k_usuario

        venta = new_venta(k_cliente,k_usuario, session["items"])
        if venta:
            flash("success", "Venta registrada!")
            return redirect(request.referrer)
        else:
            flash("error","No se registro la venta ")
            return redirect(request.referrer)

@venta.route("/sessionServicio", methods = ["POST"])
def sessionServicio():
    form_new_venta  =newVentaForm()
    k_servicio = form_new_venta.k_servicio.data.split(" - ")[0]
    print("servicio elegido !!!! ", k_servicio)
    servicio = get_servicio_by_id(k_servicio)
    if servicio:
        servicios = session.get("servicios", [])
        
        # Verifica si el servicio ya está en la lista
        if servicio not in servicios:
            servicios.append(servicio)
            session["servicios"] = servicios
            flash("success", "Servicio agregado correctamente.")
        else:
            flash("info", "El servicio ya está en la lista.")
    else:
        flash("error", "No se encontró el servicio elegido.")
    return redirect(request.referrer)

@venta.route("/eliminarItem/<k_servicio>/<k_articulo>", methods = ["GET"])
def eliminarItem(k_servicio, k_articulo):
    items = session.get("items", [])
    items = [item for item in items if item["k_servicio"] != k_servicio and item["k_articulo"] != k_articulo]
    session["items"] = items
    return redirect(request.referrer)
    
@venta.route("/sessionProducto/<k_servicio>", methods=["POST"])
def sessionProducto(k_servicio):
    form_new_venta = newVentaForm()
    k_producto = form_new_venta.k_producto.data.split(" - ")[0]
    articulo = get_articulo_by_id(k_producto)
    item = Item(k_articulo=k_producto, k_servicio=k_servicio, q_item=1, vu_item=articulo["v_articulo"])
    item_schema = ItemSchema()
    item_dict = item_schema.dump(item)

    items = session.get("items", [])
    existing_item = next((it for it in items if it["k_servicio"] == k_servicio and it["k_articulo"] == k_producto), None)

    if existing_item is None:
        items.append(item_dict)
        session["items"] = items
    else:
        flash("error", "Ya existe el producto en el servicio")

    return redirect(request.referrer)


@venta.route("/sessionItemQuantity/<k_servicio>/<k_articulo>", methods = ["PUT", "POST"])
def sessionItemQuantity(k_servicio, k_articulo):
    if request.method == 'POST':
        # Lógica para manejar la actualización de la cantidad aquí
        nueva_cantidad = request.form.get(f'cantidad_nueva_{k_articulo}')
        print("Hola Mundo, cantidad es ", nueva_cantidad)
        items = session.get("items", [])
        for i in items:
            if i["k_articulo"] == k_articulo and i["k_servicio"] == k_servicio:
                i["q_item"] = nueva_cantidad
        session["items"] = items
        return redirect(request.referrer)
    if request.method == "GET":
        redirect(url_for("venta.nuevaventa"))


@admin.route("/", methods=["GET", "POST"])
def dash():
    form_new_cliente = newClienteForm()
    form_new_articulo = newArticuloForm()
    form_new_proveedor = newProveedorForm()
    form_new_servicio = newServicioForm()
    proveedores = get_proveedores()
    if request.method == "GET":
        return render_template('admin.html', form_new_cliente = form_new_cliente, form_new_articulo= form_new_articulo, form_new_proveedor = form_new_proveedor, form_new_servicio = form_new_servicio, proveedores = proveedores)


@proveedor.route("/nuevo", methods=["POST"])
def nuevoProveedor():
    form_new_proveedor = newProveedorForm()
    if form_new_proveedor.validate_on_submit():
        nombre = form_new_proveedor.n_proveedor.data
        dir = form_new_proveedor.dir_proveedor.data
        tel = form_new_proveedor.tel_proveedor.data
        prov = register_proveedor(nombre, dir, tel)
        if prov:
                flash( "success", "Proveedor registrado exitosamente")
                return redirect(request.referrer)
        else:
                flash( "error", "Error al registrar proveedor")

app/templates/admin.html
{%extends "base.html"%}
{%block title%}
Admin
{%endblock%}
{%block contenido%}

<h1>Administrador</h1>

<br>

<div class="btn-group btn-group-lg" role="group" aria-label="Large button group">
    <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#ProveedorModal">Nuevo proveedor</button>
    <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#ArticuloModal">Nuevo producto</button>
    <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#ClienteModal">Nuevo cliente</button>
    <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#ServicioModal">Nuevo servicio</button>

  </div>



<!-- Modal -->
<div class="modal fade" id="ProveedorModal" tabindex="-1" aria-labelledby="ProveedorModalLabel" aria-hidden="true">
    <div class="modal-dialog">

      <form method="POST" action="{{url_for('proveedor.nuevoProveedor')}}" class="ajax-form">

      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Nuevo proveedor</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          {{ form_new_proveedor.hidden_tag() }}
        {{ form_new_proveedor.csrf_token }}

        <div class="mb-3">
            {{ form_new_proveedor.n_proveedor.label(class="form-label") }}
            {{ form_new_proveedor.n_proveedor(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form_new_proveedor.dir_proveedor.label(class="form-label") }}
            {{ form_new_proveedor.dir_proveedor(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form_new_proveedor.tel_proveedor.label(class="form-label") }}
            {{ form_new_proveedor.tel_proveedor(class="form-control") }}
        </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <input class="btn btn-primary" type="submit" value="Guardar">
        </div>
      </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="ArticuloModal" tabindex="-1" aria-labelledby="ArticuloModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form method="POST" action="{{ url_for('articulo.nuevoArticulo') }}" class="ajax-form">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Nuevo artículo</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ form_new_articulo.hidden_tag() }}
                    {{ form_new_articulo.csrf_token }}

                    <div class="mb-3">
                        {{ form_new_articulo.n_articulo.label(class="form-label") }}
                        {{ form_new_articulo.n_articulo(class="form-control") }}
                    </div>

                    <div class="mb-3">
                        {{ form_new_articulo.desc_articulo.label(class="form-label") }}
                        {{ form_new_articulo.desc_articulo(class="form-control") }}
                    </div>

                    <div class="mb-3">
                        {{ form_new_articulo.v_articulo.label(class="form-label") }}
                        {{ form_new_articulo.v_articulo(class="form-control") }}
                    </div>

                    <div class="mb-3">
                        {{ form_new_articulo.q_articulo.label(class="form-label") }}
                        {{ form_new_articulo.q_articulo(class="form-control") }}
                    </div>

                    <div class="mb-3">
                        {{ form_new_articulo.n_proveedor.label(class="form-label") }}
                        <input class="form-control autocomplete-proveedor" id="autocomplete-proveedor" list="proveedores-list" name="{{ form_new_articulo.n_proveedor.name }}">
                        <datalist id="proveedores-list">
                            {% for proveedor in proveedores %}
                                <option value="{{proveedor.id}} - {{proveedor.n_proveedor}}">
                            {% endfor %}    
                        </datalist>
                    </div>

                    <!-- Campo oculto para almacenar el ID del proveedor -->

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </div>
            </div>
        </form>
    </div>
</div>


<div class="modal fade" id="ServicioModal" tabindex="-1" aria-labelledby="ServicioModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form method="POST" action="{{ url_for('servicio.nuevoServicio') }}" class="ajax-form">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Nuevo servicio</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ form_new_servicio.hidden_tag() }}
                    {{ form_new_servicio.csrf_token }}

                    <div class="mb-3">
                        {{ form_new_servicio.n_servicio.label(class="form-label") }}
                        {{ form_new_servicio.n_servicio(class="form-control") }}
                    </div>

                    <div class="mb-3">
                        {{ form_new_servicio.desc_servicio.label(class="form-label") }}
                        {{ form_new_servicio.desc_servicio(class="form-control") }}
                    </div>

                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="ClienteModal" tabindex="-1" aria-labelledby="ClienteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form method="POST" action="{{ url_for('cliente.nuevoCliente') }}" class="ajax-form">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Nuevo servicio</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ form_new_cliente.hidden_tag() }}
                    {{ form_new_cliente.csrf_token }}
                
                    <div class="mb-3">
                        {{ form_new_cliente.id_cliente.label(class="form-label") }}
                        {{ form_new_cliente.id_cliente(class="form-control") }}
                    </div>
                
                    <div class="mb-3">
                        {{ form_new_cliente.n_cliente.label(class="form-label") }}
                        {{ form_new_cliente.n_cliente(class="form-control") }}
                    </div>
                
                    <div class="mb-3">
                        {{ form_new_cliente.tel_cliente.label(class="form-label") }}
                        {{ form_new_cliente.tel_cliente(class="form-control") }}
                    </div>
                
                    <div class="mb-3">
                        {{ form_new_cliente.email_cliente.label(class="form-label") }}
                        {{ form_new_cliente.email_cliente(class="form-control") }}
                    </div>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </div>
            </div>
        </form>


<script>
  $(function() {
      $.ajax({
          url: '{{ url_for("proveedor.JSONProveedores") }}'
      }).done(function (data){
          console.log(data)
          $('#autocomplete-proveedor').autocomplete({
              source: data,
              minLength: 2,
              select: function(event, ui) {
                k_proveedor = ui.item.label
                console.log("K_PROVEEDOR ES "+k_proveedor)
                  // Asigna el nombre del proveedor al campo n_proveedor
                  $('#autocomplete-proveedor').val(ui.item.label);
              }
          });
      });
  });
</script>





{%endblock%}

app/templates/base.html
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous" SameSite="none Secure">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" SameSite="none Secure">
    <script src="https://kit.fontawesome.com/151fccfd32.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar-style.css') }}" type="text/css"> 
    
    <!--NO EDITAR POR FAVOR :)))))))))))))))))))))))-->
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    
    <!--NO MOVER ESTOS SCRIPTS :))))))))))))))))))))))-->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Popper.JS -->

    <!--Estilos personalizados-->
    <link rel="stylesheet" href="{{ url_for('static', filename='style-login.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style-footer.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style-ventas.css') }}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" />    


    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.7/dist/sweetalert2.all.min.js"></script>



    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script src="{{ ASSET_URL }}"></script>

    {%block head%}{%endblock%}
    <title>{% block title %}{% endblock %}</title>

</head>

<body>
    {% include 'navbar.html' %}


<div class="container ">
    {%block contenido%}
    {%endblock%}
</div>


<br>

    <!-- Footer -->

 <!--  <div class="foot"> 
        <div class="container mt-3">

        <div class="image-logo">
        
        <img class="logo-footer" src="../static/img/logo.png" alt="">
        </div>

        <div class="contact"> 
            <h4>CRA 15# 77-05 
                LOCAL 2-84. CC 
                ALTA TECNOLOGÍA 
                TELEFONO: 601 6135655</h4>
        </div>
        <div class="social-net">
            <p>Sistema de Gestión de 
                Servicios y Ventas</p>
        </div>

    </div>

    --> 


    <!-- Footer -->



    {%block scripts%}
    {%endblock%}

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% for message, category in messages %}
    <script>
        Swal.fire({
            icon: "{{ category }}",
            title: "{{ message }}",
            showConfirmButton: true,
            timer: 5000
        });
    </script>
    {% endfor %}
    {% endwith %}


    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>






</body>

</html>

app/templates/dash_app.html
{%extends "base.html"%}
{%block title%}
Login
{%endblock%}
{%block contenido%}
<div id="dash-container">

        {{ dash_app_content|safe }}
        <iframe src="/dashapp/" width="100%" height="600px" frameborder="0"></iframe>
</div>




{%endblock%}

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>touchcenter </title>
</head>
<body>
    <h1 class="hola">Hola Mundo

    </h1>

    <h2>{{user}}</h2>

    
</body>
</html>

app/templates/login.html
{%extends "base.html"%}
{%block title%}
Login
{%endblock%}
{%block contenido%}


<h1 class="login-title">Login</h1>

<form class="form-login" method="POST" action="{{url_for('home.login')}}">
    
 
   <h3> {{ form.usuario.label }} </h3>
    
   <div class="user">
    {{ form.usuario(size=20, class_="form-control") }}
    </div>
    
    <h3>{{ form.pwd_usuario.label }} </h3>
    
    <div class="pass">
    {{ form.pwd_usuario(size=20, class_="form-control") }}
    </div>

    <div>
    <input class="btn btn-primary" type="submit" value="Login!">
    </div>
</form> 



{%endblock%}

app/templates/navbar.html
<link rel="stylesheet" href="{{ url_for('static', filename='style-navbar.css') }}" type="text/css">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{url_for('home.index')}}">

            <img class="logo_tc" src="../static/img/logo.png" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('articulo.articulos')}}">Articulos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('venta.ventas')}}">Ventas</a>
                </li>
                {% if session["user"] %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('dash_route.load_dash')}}">Dash</a>
                </li>
                {% endif %}
  
            </ul>
  
        </div>
  
        {% if session["user"] %}
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          
          <ul class="navbar-nav">
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                      data-bs-toggle="dropdown" aria-expanded="false">
                      Usuario: {{session["user"].n_usuario}}
                      
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                      <li><a class="dropdown-item" href="{{url_for('admin.dash')}}">Opciones Admin</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{{url_for('home.logout')}}">Cerrar sesión</a></li>
                  </ul>
              </li>
          </ul>
  
        {% endif %}
  
  
  
    </div>
  </nav>

app/templates/register.html
{%extends "base.html"%}
{%block title%}
Registro
{%endblock%}
{%block contenido%}

<h1>Registro</h1>
<form method="POST" action="{{url_for('home.register')}}">
    
    
    {{ form.usuario.label }} {{ form.usuario(size=20) }}
    {{ form.pwd_usuario.label }} {{ form.pwd_usuario(size=20) }}
    <input type="submit" value="Registrarme">
</form> 


{%endblock%}

app/templates/ventas.html
{%extends "base.html"%}
{%block title%}
Login
{%endblock%}
{%block contenido%}


<h1 class="vent-title">Ventas</h1>

<br>

<div class="btn-group btn-group-lg" role="group" aria-label="Large button group">
    <a href="{{ url_for('venta.nuevaventa') }}" class="btn btn-outline-primary">Registrar venta</a>
</div>


{%endblock%}